console.log(5 > 2);
console.log(10 < 20);
console.log(4 >= 4);
console.log(2 <= 2);
console.log(10 != 20);
console.log(10 > 100);
console.log(5 <= 4);
console.log(5 == 3);
console.log("Jonathan" != "vinicius");
console.log("Jonathan " != "Jonathan ");